### ISSUE TITLE
Taro 4.0.5 使用nutui开发H5项目使用UI组件后提示 Warning: Unsupported style property -webkitMask. Did you mean WebkitMask?

### ISSUE THREAD

**Issue by wangjunjun0212** [jdf2e/nutui-react#2610]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.14

### 平台

h5

### 重现链接

https://github.com/wangjunjun0212/taro-.git

### 重现步骤

import React, { useState } from 'react'
import { View } from '@tarojs/components'
import { ConfigProvider, FixedNav } from '@nutui/nutui-react-taro'
import './index.scss'
const Index = () => {
  const list = [
    {
      id: 1,
      text: '首页',
      icon: 'https://img11.360buyimg.com/imagetools/jfs/t1/117646/2/11112/1297/5ef83e95E81d77f05/daf8e3b1c81e3c98.png',
    },
    {
      id: 2,
      text: '分类',
      icon: 'https://img12.360buyimg.com/imagetools/jfs/t1/119490/8/9568/1798/5ef83e95E968c69a6/dd029326f7d5042e.png',
    },
    {
      id: 3,
      text: '购物车',
      num: 2,
      icon: 'https://img14.360buyimg.com/imagetools/jfs/t1/130725/4/3157/1704/5ef83e95Eb976644f/b36c6cfc1cc1a99d.png',
    },
    {
      id: 4,
      text: '我的',
      icon: 'https://img12.360buyimg.com/imagetools/jfs/t1/147573/29/1603/1721/5ef83e94E1393a678/5ddf1695ec989373.png',
    },
  ]
  const [visible, setVisible] = useState(false)
  const change = (value) => {
    setVisible(value)
  }
  const selected = (
    item,
    event
  ) => {
    console.log(item, event)
  }
  return (
    <View>
      首页
       <FixedNav
        list={list}
        activeText="基础用法"
        overlay
        position={{ bottom: '70px' }}
        onChange={change}
        visible={visible}
        onSelect={selected}
      />
    </View>
  )
}

export default Index

### 期望的结果是什么？

浏览器控制台正常

### 实际的结果是什么？

react-dom.development.js:86 Warning: Unsupported style property -webkitMask. Did you mean WebkitMask?
    at i
    at y2
    at j5
    at div
    at div
    at FixedNav (http://192.168.3.24:2024/@fs/D:/work/Project/User/chargeApp/node_modules/.vite/deps/@nutui_nutui-react-taro.js?v=489b43a8:4551:22)
    at taro-view-core
    at ReactComponent (http://192.168.3.24:2024/@fs/D:/work/Project/User/chargeApp/node_modules/.vite/deps/chunk-VL2AZADA.js?v=489b43a8:312:7)
    at TaroViewCore
    at Index (http://192.168.3.24:2024/pages/login/index.jsx:47:33)
    at div
    at PageWrapper (http://192.168.3.24:2024/@fs/D:/work/Project/User/chargeApp/node_modules/.vite/deps/chunk-5KPYFE7G.js?v=489b43a8:233:9)
    at App (http://192.168.3.24:2024/app.js:7:3)
    at AppWrapper (http://192.168.3.24:2024/@fs/D:/work/Project/User/chargeApp/node_modules/.vite/deps/chunk-5KPYFE7G.js?v=489b43a8:301:7)

### 环境信息

Taro v4.0.5

  Taro CLI 4.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      @tarojs/cli: 4.0.5 => 4.0.5 
      @tarojs/components: 4.0.5 => 4.0.5 
      @tarojs/helper: 4.0.5 => 4.0.5
      @tarojs/plugin-framework-react: 4.0.5 => 4.0.5
      @tarojs/plugin-html: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-alipay: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-h5: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-jd: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-qq: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-swan: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-tt: 4.0.5 => 4.0.5
      @tarojs/plugin-platform-weapp: 4.0.5 => 4.0.5
      @tarojs/react: 4.0.5 => 4.0.5
      @tarojs/runtime: 4.0.5 => 4.0.5
      @tarojs/shared: 4.0.5 => 4.0.5
      @tarojs/taro: 4.0.5 => 4.0.5
      @tarojs/vite-runner: 4.0.5 => 4.0.5
      babel-preset-taro: 4.0.5 => 4.0.5
      eslint-config-taro: 4.0.5 => 4.0.5
      react: ^18.0.0 => 18.3.1

**Comment by limuen** [comment]
+1

**Comment by nieyunliang** [comment]
你们用的vite还是webpack呢？ 我用vite然后组件没有样式
![image](https://github.com/user-attachments/assets/1a3c7f66-f7d2-4659-9034-88efefc42503)

**Comment by wangyuan0108** [comment]
据说nutui还没有全面适配taro4，有组件有bug很正常

**Comment by TuringZhu** [comment]
+1 。
1. 微信小程序没有样式（TabBar）
2. h5中提示webkitMask错误

**Comment by migozzzz** [comment]
pnpm dev:h5报错
![企业微信截图_17340561093107](https://github.com/user-attachments/assets/680dfb62-d9ca-44ce-b388-770346cd790c)

yarn dev:h5报错
![企业微信截图_17340561579985](https://github.com/user-attachments/assets/5d5962ce-30e4-4773-86fc-3b3f5cc83834)

以上都是拉取的最新的模板安装的项目，分别用pnpm、yarn，什么内容都没有添加，然后运行到h5出错的。
请问这些怎么解决？
