### ISSUE TITLE
nutui-react-taro  TextArea输入时组件内部报错

### ISSUE THREAD

**Issue by JacobChenbo** [jdf2e/nutui-react#478]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.3.10

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.21.1

### Browser and its version（浏览器及其版本）
Chrome(107.0.5304.110)

### System and its version（系统及其版本）
MacOs(12.3.1)

### Reproduction link（重现链接）
[https://codepen.io/pen/](https://codepen.io/pen/)

### Steps to reproduce（重现步骤）
import { TextArea } from '@nutui/nutui-react-taro'

<TextArea
                        className='text-area'
                        defaultValue={remark}
                        limitshow
                        maxlength={200}
                        placeholder='选填'
                        onChange={(value, event) => {
                            console.log(value);
                            // setRemark(text);
                        }}
                    />

### What is expected?（期望的结果是什么？）
onChange能正常回调用户的输入

### What is actually happening?（实际的结果是什么？）
组件内部报错：
Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at textChange (textarea.taro-388d1f90.js?da37:53:1)
    at onInput (textarea.taro-388d1f90.js?da37:83:1)
    at HTMLUnknownElement.callCallback2 (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:3734:38)
    at Object.invokeGuardedCallbackDev (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:3758:38)
    at invokeGuardedCallback (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:3792:49)
    at invokeGuardedCallbackAndCatchFirstError (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:3795:43)
    at executeDispatch (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:7002:21)
    at processDispatchQueueItemsInOrder (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:7022:29)
    at processDispatchQueue (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:7031:25)
    at dispatchEventsForPlugins (vendors-node_modules_taro_h5_prebundle_chunk-NGJSFLU2_js.js:7039:21)

**Comment by vickyYE** [comment]
已修复，会跟随下一版一起上线
